version: 2

seeds:
  - name: HDAS
    description: "Historical Driver Application Status"
    columns:
      - name: App_No
        tests:
          - unique
          - not_null

      - name: Type
        tests:
          - not_null
          - accepted_values:
              values: ["PDR", "CDR"]

      - name: Drug_Test
        tests:
          - not_null
          - accepted_values:
              values: ["Not Applicable", "Complete", "Needed"]
